### ISSUE TITLE
Finish Initial Storyboarding

### ISSUE THREAD

**Issue by jpaetsch** [CMPUT301W21T32/BooleanCatastrophe#7]
As per Project Part 2:

"Diagram the layout of your main user interface and major dialogs, with comments describing the important elements. Also, diagram storyboard sequences of using your application, with transitions between different states of the user interface, caused by the user manipulating the controls or providing input. Within the diagrams, reference the relevant requirements. Convincingly show all the requirements are covered. For a demo of storyboards: https://www.youtube.com/watch?v=5PPD0ncJU1g&list=PL240uJOh_Vb4PtMZ0f7N8ACYkCLv0673O"

**Comment by jpaetsch** [comment]
Got initial drafts; Sadav needs to submit his storyboarding flows and Usama will combine them into one larger image so it is clear how everything will work together.

**Comment by usamaa18** [comment]
Added Storyboards in Assets folder. Linked image to the wiki.
